name:                exercises

default-extensions:
- UnicodeSyntax
- MultiParamTypeClasses
- FunctionalDependencies
- FlexibleInstances

dependencies:
- base >= 4.7 && < 5
- stm
- logict

library:
  source-dirs: src

tests:
  exercises-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exercises
