name:                exercises

default-extensions:
- MultiParamTypeClasses
- FunctionalDependencies
- FlexibleInstances

dependencies:
- base >= 4.7 && < 5
- stm
- mtl
- transformers
- logict
- containers
- unliftio
- unliftio-core

library:
  source-dirs: src

